### ISSUE TITLE
Suggestion: Option to scan for DLLs using Everything

### ISSUE THREAD

**Issue by RuinTD** [Spodi/SpecialK-local-updater#8]
[Everything](https://www.voidtools.com/) is an alternative to Windows Search that keeps its own index and has a CLI. It would be useful if this tool had an option to scan for DLLs using Everything, removing the slow time it takes to enumerate files:
```bat
es.exe -path D:\Games "exact:dxgi.dll|exact:d3d11.dll|exact:d3d9.dll|exact:d3d8.dll|exact:ddraw.dll|exact:dinput8.dll|exact:opengl32.dll"
```

**Comment by Spodi** [comment]
I can look into it as an optional thing in the future, but it won't ever shipped with it by default. Cause it either needs to be installed as service or needs admin rights.
> "Everything" requires administrative privileges for low level read access to NTFS volumes for NTFS indexing.


Currently measuring and optimizing the time to enumerate the files is a hassle, cause after the first scan everything is cached by Windows and I need to restart my PC to get uncached results.
EDIT: found a programm that can clear that cache in RAM.

**Comment by Spodi** [comment]
Currently measuring and optimizing the time to enumerate the files is a hassle, cause after the first scan everything is cached by Windows and I need to restart my PC to get uncached results.

**Comment by Spodi** [comment]
May I ask how long a scan takes for you and how many games you have installed?
Did some testing on my machine and this is the result:
```
Loading cached locations... Took 0.0005237 Seconds.
Searching for registered games... Took 3.8846408 Seconds.
Scanning 146 registered game folders... Took 0.3545942 Seconds.
Done
```
The "problem" actually isn't the enum of files here.
My current (still local) dev version shaves off a second for getting the games folders.

**Comment by Spodi** [comment]
Uploaded the slightly faster version as a release.
https://github.com/Spodi/SpecialK-local-updater/releases/tag/v24.4.5

**Comment by Spodi** [comment]
I don't think "Everything" is needed anymore with this release:
https://github.com/Spodi/SpecialK-local-updater/releases/tag/v24.4.5.1
